name: gatekeeper
automanagedNamespaces: $POD_COUNT
tuningSets:
- name: UniformQPS
  qpsLoad:
    qps: 1
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1
steps:
- name: Starting measurements
  measurements:
  - Identifier: ResourceUsageSummary
    Method: ResourceUsageSummary
    Params:
      action: start
  - Identifier: APIResponsiveness
    Method: APIResponsiveness
    Params:
      action: reset
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = latency
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: v1
      kind: ReplicationController
      labelSelector: group = latency
      operationTimeout: 15m
- phases:
  - namespaceRange:
      min: 1
      max: $POD_COUNT
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: latency-pod-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        Replicas: 1
        Group: latency
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- phases:
  - namespaceRange:
      min: 1
      max: $POD_COUNT
    replicasPerNamespace: 0
    tuningSet: Sequence
    objectBundle:
    - basename: latency-pod-rc
      objectTemplatePath: rc.yaml
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
# Collect measurements
- measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather
- measurements:
  - Identifier: APIResponsiveness
    Method: APIResponsiveness
    Params:
      action: gather
- measurements:
  - Identifier: ResourceUsageSummary
    Method: ResourceUsageSummary
    Params:
      action: gather
